version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: /src/dotnet/LD.Numeric/LD.Numeric
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: /src/dotnet/LD.Numeric/LD.Numeric.Test
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: nuget
    directory: /src/dotnet/LD.Numeric/LD.Numeric.Benchmark
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
